### ISSUE TITLE
What if I'm already running appimagelauncherd

### ISSUE THREAD

**Issue by johnblommers** [mijorus/gearlever#10]
I'm running `appimagelauncherd` on my system, which monitors when I run an AppImage and offers to integrate it into the system and moving it into `~/Applications/` for me.

If I now install `gearlever` what interactions and conflicts might I expect to run into?

**Comment by mijorus** [comment]
First of all, which `appimagelauncherd ` are we talking about?😁
The AppImage dev team went through different iterations, from apps to system deamons.

By the way, if we are talking about [this](https://github.com/TheAssassin/AppImageLauncher), in my tests AppImage Launcher basically does what Gear lever does: it works like an application which can open ".appimages" files.

If you set Gear lever as the default app for ".appimages" with your file manager (just like you normally would do for any other file), you shouldn't have problems.

Please just note that if you try to uninstall apps integrated with AppImageLauncher using Gearlever, their icons will not be removed from your filesystem.
