### ISSUE TITLE
Information for alternative package maintainers

### ISSUE THREAD

**Issue by mijorus** [mijorus/gearlever#100]
Starting from version 2.0.0, which will come out in the next couple of weeks, Gear Lever will:

- Embed only icons files prefixed with either `gearlever-` or `gl-`
- Use the command`flatpak-spawn` only if it's running inside a Flatpak sandbox, otherwise the command will be executed directly
- Require access to the network (not strictly needed, but will be the whole point of v2)
- Require `python3-requests` 
- Require the `readelf` command, usually part of `binutils`

I hope this will help you out.

Cheers 

@TuxDeluxe 
@ivan-hc
.. and others I don't remember now

**Comment by TuxDeluxe** [comment]
Thanks for the heads-up, this should make packaging gearlever easier. Looking forward to the new updates!
