### ISSUE TITLE
documentation for devs on adding AppImage update support

### ISSUE THREAD

**Issue by aarron-lee** [mijorus/gearlever#104]
Is there documentation anywhere for devs on adding AppImage update support as described by https://mijorus.it/posts/gearlever/update-url-info/

**Comment by mijorus** [comment]
> Is there documentation anywhere for devs on adding AppImage update support as described by https://mijorus.it/posts/gearlever/update-url-info/

Gear Lever can read update information directly from the embedded data, as specified in the App image standard.

https://docs.appimage.org/packaging-guide/optional/updates.html

**Comment by aarron-lee** [comment]
thank you, I didn't know that the AppImage standard had a specification for updates. I had assumed the gear lever implementation was a bespoke implementation.
