### ISSUE TITLE
Snap package

### ISSUE THREAD

**Issue by Master811129** [mijorus/gearlever#107]
Please make a snap package for this.

**Comment by Callen44** [comment]
I can say I would also like this, there are many users of Ubuntu and other Ubuntu forks (like Kubuntu) that may not care to add flatpak to their system and may simply never discover this great app. I understand that a lot of people have bitter sentiments about snapcraft, and I understand why, but they have gotten better at many of those things and so it might be worth looking into just how hard this theoretically might be. Not all users of Linux are fully immersed in the Linux world, and these are the people the least likely to have _both_ flatpak and snapcraft on their system, if it's not too hard maybe it's a good idea to add support for both, but if it is too hard to support two versions I totally understand.

**Comment by Deewens** [comment]
I agree, would be cool to see a snap version of the app :) !

**Comment by mijorus** [comment]
Hi, 
I don't have any sentiment about Snap or anything like that, I just don't have enough time to carefully maintain both packages.

I'm sorry

**Comment by Callen44** [comment]
That's all right, I understand.
