### ISSUE TITLE
Problem with new update function in v2

### ISSUE THREAD

**Issue by Sander50** [mijorus/gearlever#112]
Hi, I love Gearbox! Just experiencing a problem with the new update function in version 2.
This is what happens for me:
1) Install Trezor Suite latest version from their website, v24.6.2 at the moment, https://trezor.io/trezor-suite
2) Add Github update URL, I checked multiple times and I think this should be correct: https://github.com/trezor/trezor-suite/releases/download/*/Trezor-Suite-*-linux-x86_64.AppImage
3) URL becomes green and is accepted by Gearbox
4) Gearbox now detects an update for Trezor Suite, click the Update button
5) Gearbox now "updates" to version "24.5.4.4216" (I don't understand where ".4216" comes from, as the original version on Github is called 24.5.4)
6) Obviously it downgraded, but Gearbox thinks it is at the latest version

**Comment by mijorus** [comment]
All right, apparently the github apis say that the latest release is 24.5 for some reason.
Some caching issue from github, maybe? 

I don't consider this to be an issue with Gear Lever, let's wait a few hours and see what happens. If the issue persists, I will investigate further.
See the two links below


https://api.github.com/repos/trezor/trezor-suite/releases/latest
https://api.github.com/repos/trezor/trezor-suite/releases?per_page=1

**Comment by mijorus** [comment]
Update: after a bit of investigation, I guess that what is probably happening here is that they crafted a release manually but forgot to mark it as latest.

There is nothing wrong with Gear Lever here. It's just the way Github releases work
