### ISSUE TITLE
Translation Portuguese Brazil

### ISSUE THREAD

**Issue by IsaacDias2020** [mijorus/gearlever#115]
Nice app.
How can i help to translate to Portuguese Brazil?

**Comment by mijorus** [comment]
Hi, if you speak portoguese and you want to contribute, please do this:

- Download Poedit: https://poedit.net/
- Clone this repo with: `git clone https://github.com/mijorus/gearlever.git`
- With poedit, open the file called `gearlever/po/gearlever.pot`
- You should see a button "create new translation" on the bottom right corner, you should select portoguese-brazil
