### ISSUE TITLE
problem with appImage Joplin

### ISSUE THREAD

**Issue by HDInfautre** [mijorus/gearlever#118]
hello
I just discovered with joy your application.
I feel that it will be very useful to me and I will answer all the forums where I launched the request to have an update of my appImages and the icons in my Ubuntu 24.04  :-)

Until now all the methods based on .desktop, see other applications like menuLibre .... had failed.
Maybe because I have all my applications in a subfolder on a portable hard drive
/media/rv/donnees/ComInformat./Appli-donnees-port

I still have a problem with Joplin https://joplinapp.org/
I do the same method as the others but it will find me a bad icon! but above all it does not launch the application that I stored in my tree (see the photos).
Can you help me manage Joplin?

Finally, subsidiary question: if I understand correctly, I am obliged to double the appImages ? because I want to keep my initial tree.
And a request if it was possible to manage your own icon because I have some appImages for 2 different profiles
Regards
![Capture d’écran du 2024-07-26 15-56-23](https://github.com/user-attachments/assets/e968f092-8e48-46ad-8ece-1153f5e3f860)
![Capture d’écran du 2024-07-26 15-54-59](https://github.com/user-attachments/assets/5282ce2b-d99a-4681-9775-2c0ccf46e395)
![Capture d’écran du 2024-07-26 15-54-22](https://github.com/user-attachments/assets/f286e8dd-a465-4277-841f-48d35bd38bbf)
![Capture d’écran du 2024-07-26 15-54-04](https://github.com/user-attachments/assets/3610e683-bdf2-43f9-a303-eb313973f174)

**Comment by mijorus** [comment]
Hi, the icon issue will be fixed in the next release.

I'm not sure about your second question.
You can choose between cloning an moving appimages already in the settings...

**Comment by HDInfautre** [comment]
Hi
Thank you for your quick response and the consideration for the icon.
I will try to formulate better

1/ bug when launching Joplin
If I launch Joplin from your application, it does not launch the application with my data source from my Joplin.AppImage.home directory!

2/ icon suggestion
Is it possible to load an icon yourself because I have 2 different directories/profiles for some appImage (like Joplin)?

3/ As I have a directory with data of type .config or .home, I want to keep the original location. If I understand correctly, I am obliged to keep a duplicate under /home/rv/AppImages/... ?

**Comment by mijorus** [comment]
Hi, I think all your questions refer in some way to  the [portable mode](https://docs.appimage.org/user-guide/portable-mode.html?highlight=home) which was recently added.

GearLever does not support "portable mode" at the moment, so you would need to create this folder in ~/AppImages yourself. But still, this is not a feature I am currently testing.

**Comment by HDInfautre** [comment]
HI
Ok thanks for the answer
1/ & 3/ Your application copied a duplicate of the appimage under /home/rv/AppImages/...
And this works for several applications (except Joplin), I have the icon in the Ubuntu bar :-).
Did you understand this (because of my bad translated English!)?

2/ is this something possible?

**Comment by HDInfautre** [comment]
Hi
I just saw that there is a new version 2.0.4
Your application does not check up on itself?
How to do the update? I did not manage it in command line mode?
Can you clarify your answers to my previous questions?
Regards

**Comment by HDInfautre** [comment]
Hi
Ok I just understood that with the type of applications like Joplin, you have to apply xxx
I succeeded :-) by putting:
https://github.com/laurent22/joplin/releases/download/*/Joplin-*.AppImage

I also understand that I did the update in your directory and that it is not duplicated in my folder
/media/rv/donnees/ComInformat./Appli-donnees-port/Joplin
Is this in your roadmap?

Can you also answer the last other questions?

**Comment by mijorus** [comment]
Sorry, I got lost between all the questions.
Could you reformulate them ?

**Comment by HDInfautre** [comment]
Hi
Ok
**1/ update your extension**
I did the manual update by chance because I was not notified.
Does your extension inform us and maybe update automatically?

**2/ portable version update**
I see that the appImage has been downloaded in the directory you provided. By adding the application path, I saw an update in your directory.
Have you programmed to add a parameter with the user path (at my place /media/rv/donnees/ComInformat./Appli-donnees-port/Joplin) to do the update without going through your directory?

**3/ image change**
Less important but I was wondering if we could one day download our own icon?

**4/ digikam**
I couldn't put the right path
I see https://www-ftp.lip6.fr/pub/X11/kde/stable/digikam/8.4.0/digiKam-8.4.0-Qt6-x86-64.appimage
I put, without success, in static url:
https://www-ftp.lip6.fr/pub/X11/kde/stable/digikam/*/digiKam-*-Qt6-x86-64.appimage

**Comment by mijorus** [comment]
1/ It does not anymore. there are some issues Github's rate limiting restrictions, so I have disabled it

2/ Portable mode is not supported and is not in my roadmap

3/ This is also not on my roadmap, I see Gear Lever as a tool designed to integrate appimages, not a customization tool.

4/ Globed are not supported with Static URLs, it should be a direct link to something like **example.com/latest.appimage**.  I the case of digikam, it looks like there is no way to specify an update url.

I hope these answers all your questions.

**Comment by HDInfautre** [comment]
HI
ok thanks for these answers :+1: 
sad for the 2/, I hope that other requests will make you change your mind.
