### ISSUE TITLE
why are arbirtary numbers added to the appimage name?

### ISSUE THREAD

**Issue by Dnkhatri** [mijorus/gearlever#119]
Why is qbittorrent.appimage is not saved as qbittorrent.appimage instead it has some numbers in between?

**Comment by mijorus** [comment]
Hi, 
if you are using the latest version, it should add numbers unless there are some files with the same name in the target folder

**Comment by mijorus** [comment]
should not, wait for version 2.0.4 to be released on flathub

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
