### ISSUE TITLE
Can't update from beeper update URL

### ISSUE THREAD

**Issue by Magnusretrotech** [mijorus/gearlever#120]
When I enter the Beeper appimage download link, it doesn't work.

![image](https://github.com/user-attachments/assets/169d5a20-7a4b-4eeb-acee-27152b3cd4b0)

**Comment by mijorus** [comment]
Hi, version 2.0.4 should fix this, let me know if it works for you

**Comment by Magnusretrotech** [comment]
Yes, that fixed it
