### ISSUE TITLE
AppImage type detection wrong

### ISSUE THREAD

**Issue by probonopd** [mijorus/gearlever#132]
As per the [AppImageSpec](https://github.com/AppImage/AppImageSpec/blob/fb05d9e1b8b8616dbeb7491303edc537dca573f3/draft.md#image-format), currently there are only two _image formats_: Types 1 and 2.

* Type 1 can be identified by checking for the magic hex `0x414901` at offset 8.
* Type 2 can be identified by checking for the magic hex `0x414902` at offset 8.

So why is this talking about a type 3 then?

Also, the types exist as alternatives, and they are not called "generation".

https://github.com/mijorus/gearlever/blob/3702f37b0e2e35d0fe516d15121c7081da9a19ed/src/providers/AppImageProvider.py#L466-L481

The fix would be something like this (untested):

```
def get_appimage_type(self, el: AppImageListElement) -> int:
    file = Gio.File.new_for_path(el.file_path)
    try:
        with open(file.get_path(), 'rb') as f:
            magic = f.read(4)
            if magic == b'\x41\x49\x01':  # 0x414901
                type = 1
            elif magic == b'\x41\x49\x02':  # 0x414902
                type  = 2
      except Exception as e:
          type = 0

    return type
```

Related:
* https://github.com/ivan-hc/AM/issues/818

**Comment by mijorus** [comment]
Hi, @probonopd, thanks for clarifying that and partecipate on this thread.
I think it would be beneficial for this project if we could collaborate more ofter.

With that said, can you please clarify what is the status of [this draft](https://github.com/TheAssassin/type3-runtime)?

Also, there are some appimages that, in fact, as of today, test as Type 3 according to the code at line 476.
How should I consider them?

**Comment by mijorus** [comment]
And by the way, @probonopd, not related but still interesting to discuss, do you have proposals to replace `7z` with something else to extract the files from an appimage?

I know `--appimage-extract` exists, but that would extract all the files and it much slower, plus it does not work with Type 1 appimages.

**Comment by probonopd** [comment]
> I think it would be beneficial for this project if we could collaborate more ofter.

Indeed, happy to! Just ping me @probonopd when you need to ask or discuss something related to the AppImage format.

> With that said, can you please clarify what is the status of [this draft](https://github.com/TheAssassin/type3-runtime)?

Brainstorming.

The official AppImageSpec is at https://github.com/AppImage/AppImageSpec and is hopefully going from draft to release status soon-ish. Only thereafter the real discussions about a potential future type 3 image format might take place.

> Also, there are some appimages that, in fact, as of today, test as Type 3 according to the code at line 476.
> How should I consider them?

Check the magic values specified in https://github.com/AppImage/AppImageSpec/blob/master/draft.md#specification and mentioned above. If it doesn't have any of those, then it is not a type 1 or type 2 AppImage, and no higher numbers currently exist.

> do you have proposals to replace 7z with something else to extract the files from an appimage?

For type 2, `unsquashfs` with the offset option. For type 1 some tool that can handle zisofs compressed ISO images. Maybe libarchive?

> I know --appimage-extract exists, but that would extract all the files and it much slower, plus it does not work with Type 1 appimages.

You can specify the files you want to have extracted by `--appimage-extract`, e.g., `'/.DirIcon'`.

**Comment by mijorus** [comment]
btw, @probonopd, the function should probably be like this:

```py
    def get_appimage_generation(self, el: AppImageListElement) -> str:
        appimage_type = 0
        with open(el.file_path, 'rb') as f:
            magic = f.read(11)[-3:]

            if magic == b'\x41\x49\x01':  # 0x414901
                appimage_type = 1
            elif magic == b'\x41\x49\x02':  # 0x414902
                appimage_type  = 2

        return str(appimage_type)
```

**Comment by probonopd** [comment]
We need to read 3 bytes at offset 8, so more like `f.read(11)[8:11]`?
