### ISSUE TITLE
Consider restricting filesystem access

### ISSUE THREAD

**Issue by jtherrmann** [mijorus/gearlever#143]
For me, the app still works if I edit the permissions using Flatseal as follows:

* Remove access for "All user files"
* Add access for "Other files":
    * `~/AppImages`
    * `~/.local/share/applications`

Have you considered making these the default permissions so that Gear Lever cannot access all user files?

**Comment by mijorus** [comment]
Gear Lever gives the ability to customise the destination folder for your appimages.

It can also list appimages that have a desktop file but are located in other folders.
