### ISSUE TITLE
Update URL error for butt

### ISSUE THREAD

**Issue by dik23** [mijorus/gearlever#146]
I'm using the appimage for this software  : https://danielnoethen.de/butt/

Releases are found here : https://danielnoethen.de/butt/release/

Releases follow this pattern : https://danielnoethen.de/butt/release/*/butt-*-x86_64.AppImage

Both Static and Github URL end in a red Update URL box and the url isn't saved

![image](https://github.com/user-attachments/assets/755f7eb3-26cb-4c0e-a441-dbb5b6a59b1c)

**Comment by mijorus** [comment]
This URL is not supported.
This is not a Github release nor a static link to a file
