### ISSUE TITLE
Error on running some applications

### ISSUE THREAD

**Issue by antonio-petricca** [mijorus/gearlever#149]
When I try to run **Lens** or **LibreCAD** I get the following error (under Windows 10 + WSL 2):

> flatpak run it.mijorus.gearlever
Logging to file /home/antonio/.var/app/it.mijorus.gearlever/cache/logs/gearlever.log
MESA: error: ZINK: failed to choose pdev
libEGL warning: egl: failed to create dri2 screen
[54217:0829/114124.407713:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[54217:0829/114124.407805:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
RS_DEBUG::setLevel(3)
RS_DEBUG: Critical
RS_DEBUG: Errors
RS_DEBUG: Warnings
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

**Comment by mijorus** [comment]
Hi, 
this has nothing to do with Gear Lever, This is a problem with the app itself, more likely with the fact that WSL might not have a display properly configured as an output
