### ISSUE TITLE
Update URL for UpNote AppImage not accepted

### ISSUE THREAD

**Issue by maniadevice** [mijorus/gearlever#150]
As mentioned, the static download link for UpNote https://upnote.sfo3.cdn.digitaloceanspaces.com/UpNote.AppImage is not accepted by Gear Lever.

![image](https://github.com/user-attachments/assets/5bcf9b4a-59e0-420d-8ef4-62c9f053cfb7)

**Comment by maniadevice** [comment]
If this is something UpNote devs need to fix, please let me know. Many thanks.

**Comment by mijorus** [comment]
Hi, 
version 2.0.7 should fix this.

Thank you

**Comment by maniadevice** [comment]
Confirmed as fixed, thanks!

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
