### ISSUE TITLE
Auto Update on OS startup?

### ISSUE THREAD

**Issue by glaicodes** [mijorus/gearlever#158]
It would be really awesome if the app checked for an update on OS startup and update if there's one pending with a notification. I don't know if it's possible since I am fairly new to linux but I think people would enjoy it.

**Comment by sandenbergmelo** [comment]
I agree. That would be great.

**Comment by mijorus** [comment]
Hi, 
the latest update will include a new option in the settings to check for updates on system startup.
Gear Lever will send a notification if new updates are found, but they will not be installed automatically

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
