### ISSUE TITLE
Appimages not showing up inside Gear Lever if they are on an external drive

### ISSUE THREAD

**Issue by lollocosta123** [mijorus/gearlever#159]
I have a steam deck with just 64gb of space, in order to download some extra apps i have an sd card in which i placed the appimages and then i launch them from there.
The sd card is always inside the steam deck so it's kind of like additional internal storage for me.

I tried to add the folder in the "preferences" -> "Appimage default location" but it seems like it only wants things inside my home folder.
So what i did is I created a symlink, made sure the app had access to the new folder in the sd card and everything else.

When "installing" a new app, everything seems fine.
I download the appimage in my download folder (in the steam deck internal storage), Gear Lever asks me to "unlock" the app, i click it, i click "add to library" and it correctly moves the app from the download folder to the folder in my sd card ( via the symlink ). And then i can launch the app without any problem.

But the apps do not appear in the Gear Lever "library" meaning i can't tweak them/update them from there.
![Screenshot_20240919_160810](https://github.com/user-attachments/assets/7dc1be6f-8ace-4a69-9d47-4c7407458f94)

The app is able to move the apps in the folder that i want, shouldn't it also be able to see them after "installing" them and manage them ?

I tried with creating a symlink for the entire folder where i want the app to be in and also i tried creating a real folder in my /home/ and then creating an individual symlink for each .appimage file.
None of the two methods above worked.

Because i believe I'm not the only person that is space limited on my device internal storage, it would be very nice if the app could properly handle installing (without having to first create a symlink) and than managing the apps in an external drive.
Especially because i think appimages are the only universal app format in linux that can even launch from an external drive ?

**Comment by mijorus** [comment]
Hi, the latest update includes new permissions to allow reading files from external drives

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
