### ISSUE TITLE
Auto-update does not work for ente-auth Appimage

### ISSUE THREAD

**Issue by thariq-shanavas** [mijorus/gearlever#165]
Hello!

I sincerely hope this is not due to user error - I've been struggling to get auto-updates to work for ente auth for months.

The update URL is this:
https://github.com/ente-io/ente/releases/download/auth-v4.0.2/ente-auth-v4.0.2-x86_64.AppImage

Gear lever updates the app to v4.0.2 if I paste the url above in the 'Update URL' section. It obviously does not update to a newer version if the version number and tag are not replaced with asterisks. However, neither of the following formatted links work even when the installed version is outdated:

https://github.com/ente-io/ente/releases/download/*/ente-auth-*-x86_64.AppImage
https://github.com/ente-io/ente/releases/download/*/ente-auth-v*-x86_64.AppImage

I believe I've followed the correct instructions from here: https://mijorus.it/posts/gearlever/update-url-info/

Please let me know if I'm doing something wrong. Thanks in advance!

**Comment by mijorus** [comment]
Hi, 
this is an old issue that keeps popping up.

On Github, the latest release should be marked as "Latest" by the developer.
It looks like Ente's developers are not doing this.

If you look at the badge close to the release titles, you can see that an old 0.9 release is still marked as the latest.
Please, submit a bug report to the developer to asking them to update their release scripts to fix this issue

![image](https://github.com/user-attachments/assets/737bbb6c-f1ba-4f18-86f5-67109efc985f)

**Comment by thariq-shanavas** [comment]
Ente publishes both their photos app and authenticator app from the same repo. The 'latest' tag is applied to their flagship product, Ente Photos. Unfortunately, I doubt they'd be willing to split the photos and authenticator repos, or apply the 'latest' label for Ente Auth.

Thank you for helping me understand the cause of this issue. I'll update the app  manually when new updates are released.

**Comment by candrapersada** [comment]
how to use [Continuous build](https://github.com/ivan-hc/MPV-appimage/releases/tag/continuous)
https://github.com/ivan-hc/MPV-appimage/releases/download/continuous/MPV-Media-Player_0.39.0-3-archimage3.4.4-2.1-x86_64.AppImage
