### ISSUE TITLE
Gear Lever runs on Gnome 45 runtime when it should run on Gnome 46 runtime

### ISSUE THREAD

**Issue by CodeShakingSheep** [mijorus/gearlever#167]
Hi,
I'm using the flatpak of Gear Lever. On my system Gear Lever is the only app running on Gnome 45 runtime. All other apps are already running on Gnome 46 or 47 runtime. So, I would like to get rid of Gnome 45 runtime. When I check my installed flatpaks with `flatpak list --columns=runtime,name,ref` this is the output for Gear Lever:
```
org.gnome.Platform/x86_64/45                                  Gear Lever                                                    it.mijorus.gearlever/x86_64/stable
```
Gear Lever version according to the About tab is 2.1.0. What's confusing for me is that here https://github.com/mijorus/gearlever/blob/master/it.mijorus.gearlever.json#L4 it states that the runtime version is 46 (and not 45). What can I do to run Gear Lever on Gnome 46 runtime?

Thank you.

**Comment by CodeShakingSheep** [comment]
I think I found the reason for it. In Gear Lever's Flathub repository, the runtime version is set to 45, see https://github.com/flathub/it.mijorus.gearlever/blob/master/it.mijorus.gearlever.json#L4.

@mijorus Could you kindly update the runtime version to 46 in the flathub repo? Thank you.

**Comment by mijorus** [comment]
The runtime version has been updated. Thank you

**Comment by CodeShakingSheep** [comment]
@mijorus It doesn't seem so. It still says version 45, see https://github.com/flathub/it.mijorus.gearlever/blob/master/it.mijorus.gearlever.json#L4
The version needs to be updated directly in the Flathub repo. Thank you.

**Comment by mijorus** [comment]
Two days ago the deploy failed for some reason. Should be ok now
