### ISSUE TITLE
[Not a bug]: Differences to appimaged.service

### ISSUE THREAD

**Issue by iluvatyr** [mijorus/gearlever#172]
As someone who frequently uses AppImages. I saw several possibilities to integrate them into the Desktop environment.

The problem is just to understand the difference in features.

Is it possible to put it into the README.md how this is distinguishing itself from  the [appimaged.service](https://github.com/probonopd/go-appimage/blob/master/src/appimaged/README.md) ?

**Comment by mijorus** [comment]
Well the differences should be pretty simple for anyone how uses linux.

AppimageD is a deamon which is supposed to do stuff in the background, this is just an app.
