### ISSUE TITLE
add SHA256 hash generation

### ISSUE THREAD

**Issue by eivinh** [mijorus/gearlever#174]
Please add SHA256 hash to the list of generated hashes. Some AppImages (in my case Inkscape 1.4) are only listed with SHA256 hash.

A workaround is of course to check it on the command line with sha256sum, but it detracts from the otherwise very smooth user experience with gear lever.

If there was a way to verify the hash with clipboard copy/paste, that would be great, but I guess that would be another feature request.

Cheers,

Eivind

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus

**Comment by eivinh** [comment]
Thanks, I saw it in a flatpak update I got today. :sunglasses:
