### ISSUE TITLE
 [Feature Request] Add the list of managed AppImages as "front page"

### ISSUE THREAD

**Issue by frankven2ra** [mijorus/gearlever#18]
Basically title.
I would like to avoid "bloating" my menu with loads of apps, but i would like to launch my appimages from yours.

Grazie, ottimo lavoro!

**Comment by mijorus** [comment]
Basically, you don't want Gear lever to create app menu shortcuts, am I right?

**Comment by frankven2ra** [comment]
Yes I want to do that too, and don't get me wrong I like the app, but a
launcher or a list of managed appimages would be a cool feature, allowing
to choose which apps I want to show in the app menu.

Il lun 26 giu 2023, 13:29 Lorenzo Paderi ***@***.***> ha
scritto:
