### ISSUE TITLE
Question: installation procedure

### ISSUE THREAD

**Issue by lamyergeier** [mijorus/gearlever#180]
Readme

> Get the [[bundle from github](https://github.com/mijorus/gearlever/releases)](https://github.com/mijorus/gearlever/releases) (no auto-updates)
> 
> # From your Downloads folder
> flatpak install --bundle --user gearlever.flatpak

Do we need to download the zip file from release and extract it and run the above command? I did this but installation failed!

**Comment by mijorus** [comment]
Hi, there was a bug in the release script. Now the latest release should include the flatpak package as well

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
