### ISSUE TITLE
Update issue (XnView)

### ISSUE THREAD

**Issue by ikyquocked** [mijorus/gearlever#181]
Hello. I'm using XnView appimage
This is a static link for updates
https://download.xnview.com/XnView_MP.glibc2.17-x86_64.AppImage
if I paste it in the link field it becomes red and update-check doesnt work
Gear Lever 2.1.0
![Screenshot from 2024-10-29 19-18-35](https://github.com/user-attachments/assets/1853d59b-0c24-4adb-9f3f-81e3623bb787)

**Comment by mijorus** [comment]
GearLever always tries to check the URL to make sure that you don't paste in a random link that points to an invalid file. Unfortunately, it looks like XnView is not including any metadata in the response, which means GearLever can't validate the file.

I think the checks should stay on, to improve the user experience. You can try to contact them if you want and tell them about it, asking to include at least the content-type header in the response.
