### ISSUE TITLE
GearLevel is downloading the wrong AppImage file

### ISSUE THREAD

**Issue by Nanito111** [mijorus/gearlever#182]
[Beekeeper Realeases](https://github.com/beekeeper-studio/beekeeper-studio/releases/)

I have this URL for updates
`https://github.com/beekeeper-studio/beekeeper-studio/releases/download/*/Beekeeper-Studio-*.AppImage`

Regular version
`https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.6.8/Beekeeper-Studio-4.6.8.AppImage`

The one that GearLevel downloads
`https://github.com/beekeeper-studio/beekeeper-studio/releases/download/v4.6.8/Beekeeper-Studio-4.6.8-arm64.AppImage`

The problem is that GearLevel gets the arm version because it first than the regular version on the releases list, I think that it would be good to have an advanced option for pattern matching where you can put regex to treat this situations.

**Comment by sent44** [comment]
I am getting the same problem but with (illegal) Youtube Music
https://github.com/th-ch/youtube-music/releases/tag/v3.6.2

**Comment by mijorus** [comment]
I'm working on this

**Comment by mijorus** [comment]
No changes are required from your side, you can still use the same update url.

`https://github.com/beekeeper-studio/beekeeper-studio/releases/download/*/Beekeeper-Studio-*.AppImage`

Everything will be done under the hood

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
