### ISSUE TITLE
included updater URL incorrecly thought to be wrong

### ISSUE THREAD

**Issue by OhNoOhNOOO** [mijorus/gearlever#184]
when trying to update prism launcher, gear lever will not notice an update and i will see this message in the logs

> 2024-11-03 15:49:28,208 WARNING [utils.py:137] Provided url "gh-releases-zsync|PrismLauncher|PrismLauncher|latest|PrismLauncher-Linux-x86_64.AppImage.zsync" is not a valid url

this is weird, because both AppimageLauncher and AppImageUpdate recognize the provided url as valid and will update the application properly

**Comment by mijorus** [comment]
Hi, that warning message is fine, because it runs a series of tests under the hood.
I tested it by downloading an older version of Prism Launcher and it updated just fine.

Are you sure that you are not already running the latest version ?

**Comment by OhNoOhNOOO** [comment]
huh, was trying to update from 8.4 to 9.1 but it wasn't working yesterday. Today i come back and it worked. Might be some sort of issue on my end then? Closing since it seems like a me issue and not a problem with Gear Lever.

**Comment by mijorus** [comment]
> huh, was trying to update from 8.4 to 9.1 but it wasn't working yesterday. Today i come back and it worked. Might be some sort of issue on my end then? Closing since it seems like a me issue and not a problem with Gear Lever.

GitHub has a hard limit of 60 requests per minute from the same IP. Sometimes it happens

**Comment by OhNoOhNOOO** [comment]
might've been me using a vpn then, probably just a bunch of people making requests to github or smth on that server.

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
