### ISSUE TITLE
division by zero with firealpaca appimage

### ISSUE THREAD

**Issue by ayunami2000** [mijorus/gearlever#187]
https://firealpaca.com/download/linux

![image](https://github.com/user-attachments/assets/a8de860d-422d-4df5-ac87-425aab253e74)

![image](https://github.com/user-attachments/assets/ade708c0-8201-4ee6-839b-b8b13c90dae1)

it says division by zero when trying to update. my guess? it possibly doesnt report the total file size and gearlever may not account for this.

ALSO it thinks there is an update available even though there is not.

i think it should check the attachment **file name** to see if there is a version change for firealpaca. when downloading from the link, it will save as an appimage including the version number in the name of the file.

**Comment by mijorus** [comment]
hi there! I can fix the issue regarding the division by zero, but the update systems will probably never work on this app, unless the developers do some updates on their side

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
