### ISSUE TITLE
Nextcloud: Icon not added to top bar in Gnome

### ISSUE THREAD

**Issue by andreas1107** [mijorus/gearlever#19]
Hi, thank you for this app - it's much needed and very useful. 

I noticed after I added the latest Nextcloud AppImage to Gear, the icon in the top-right corner is no longer visible (Mpris label).

However it seems Nextcloud is still running. I find the icon quite useful to remind me that the app is running and whether syncing or not. 

![image](https://github.com/mijorus/gearlever/assets/34312687/dde4e96c-5b7a-45ff-894a-43b459a8f10c)

Also I notice that the icon added to launcher misses the Nextcloud graphics, but it does show it Gear. 

![image](https://github.com/mijorus/gearlever/assets/34312687/e62e17dc-5920-4989-b89c-1dd881cb50dd)

However in Gear App, the icon works correctly: 

![image](https://github.com/mijorus/gearlever/assets/34312687/dcfbee8a-9d14-49ca-8b55-cd8d51be6f38)

Debian GNU/Linux 12 (bookworm) (64-bit)
Gnome: 43.4 using Wayland

Gear: 1.0.8
Nextcloud: Version 3.9.0 (Debian)

Thanks!

--- 

Edit: 

Perhaps a bug with the Gnome extension?
https://github.com/ubuntu/gnome-shell-extension-appindicator

After enabling/disabling the extension the Nextcloud app icon is there:

![image](https://github.com/mijorus/gearlever/assets/34312687/71917701-e50f-4696-8b57-8bfdd98c0752)

**Comment by mijorus** [comment]
Does it work now?

**Comment by andreas1107** [comment]
Yes, it works - thank you!
