### ISSUE TITLE
Release the App on Flathub Beta for now

### ISSUE THREAD

**Issue by Heus-Sueh** [mijorus/gearlever#2]
## Motivation
I didn't have much success trying to compile the project

## Suggestion
release the app on flathub beta for enthusiasts who are looking forward to it

## Other
or is the app almost ready to launch?

**Comment by mijorus** [comment]
hi, the app is in good shape but I want to add some more features before the release.

compiling it is quite easy, you can either grab the latest .flatpak from the releases tab or, my personal suggestion, open this project with Gnome Builder and press RUN

**Comment by 3laws** [comment]
> compiling it is quite easy, you can either grab the latest .flatpak from the releases tab or, my personal suggestion, open this project with Gnome Builder and press RUN

Any special arguments for when building for non-flatpak systems?
