### ISSUE TITLE
"Click the '+' icon" message is confusing (there are two "+" icons!)

### ISSUE THREAD

**Issue by cincodenada** [mijorus/gearlever#25]
Hello, I just installed GearLever and so far it's been great, did what I needed it to smoothly (moved my app images to a common folder, added them to the applications folder!)

A small onboarding issue: the help text when you don't have any apps says "click the + button", but of the five buttons in the menu bar, _two_ of them are "+" buttons :sweat_smile: 

I don't actually know what the righthand set of +/- buttons does - clicking them doesn't seem to have any effect on my installation - but could we change one of these buttons so it's less confusing? Maybe use a magnifying glass if that's what the right-hand set is for? Or maybe an "open" icon for the left-hand "+"?

Lots of options, obviously just changing the help text to "click the + button in the upper-left corner" would do it too, verbose, but might be good anyway so folks don't have to go looking around for where the plus button is

**Comment by mijorus** [comment]
Hi @cincodenada , I see your point. 

Some distributions use the + icon to trigger full screen mode, I did not think about it.

Can you please tell me distro are you using? So I can run some tests to improve the UX.

**Comment by mijorus** [comment]
Gear lever now has a (+ Open) label which should make things easier to understang
