### ISSUE TITLE
Please remove application/vnd.flatpak.ref from mimetype in the desktop file

### ISSUE THREAD

**Issue by senntore** [mijorus/gearlever#27]
Issue: I cannot install .flatparef files using the gui flatpak-installer  because the mimetype in the desktop file includes flatpakref along with appimage.

Previously I've tried to remove that part in the desktop file & it works great(from next login) but after an update the desktop file resets.

So please fix this issue.

Screenshot:
![image](https://github.com/mijorus/gearlever/assets/58325574/5b21dfdb-aae9-41a2-99dc-68631333a875)
Note: I cannot change the default to flatpak-installer because for some reason I can't find it in the available options.

This is the default behavior when gear lever is not installed or when it does not have flatpakref in the mimetype:
![image](https://github.com/mijorus/gearlever/assets/58325574/7e71f424-319e-4d8d-8c01-3246a39e9d04)

which leads to
![image](https://github.com/mijorus/gearlever/assets/58325574/aa8a8c83-4e20-4efc-a7de-bcc2776db3fc)

OS: Pop!_OS 22.04
Version: 1.0.11

**Comment by mijorus** [comment]
version 1.0.12 has been released with a fix. Sorry about that, it was a leftover
