### ISSUE TITLE
[Suggestion] "add" button at top left

### ISSUE THREAD

**Issue by Heus-Sueh** [mijorus/gearlever#3]
![image](https://github.com/mijorus/gearlever/assets/98482469/ee62fe65-57d7-473f-8f3b-e3afac70d6cf)
something similar to bottles only its function would be to add the AppImages
![image](https://github.com/mijorus/gearlever/assets/98482469/8d036061-0d91-4df7-ae19-fff148b60d92)

**Comment by Heus-Sueh** [comment]
![image](https://github.com/mijorus/gearlever/assets/98482469/977b30d9-782a-4feb-9f5c-39553cbbe65d)
or something similar to gnome boxes

**Comment by mijorus** [comment]
Added with 58e48ebbf56b023c40988e8cd808cd0ef3aceb3a

**Comment by Heus-Sueh** [comment]
maybe we can add a description of what the button does or will do
like bottles:
![image](https://github.com/mijorus/gearlever/assets/98482469/72d8cb00-24b9-4181-a294-8f190b159723)

A question, do you intend to try to be part of the [GNOME Circle](https://circle.gnome.org/)?

**Comment by mijorus** [comment]
Not at the moment, they usually require some modifications before they approve your project, little things that require extra work, and with the lack of a good documentation those small changes could take hours.

**Comment by Heus-Sueh** [comment]
> Not at the moment, they usually require some modifications before they approve your project, little things that require extra work, and with the lack of a good documentation those small changes could take hours.

I understood, your app is very good it makes the AppImages much better to use

**Comment by mijorus** [comment]
thanks
