### ISSUE TITLE
Flatpak theme issue

### ISSUE THREAD

**Issue by wingedonezero** [mijorus/gearlever#30]
This only occurs when i open the gearlever app it self to show the list of integrated appimages. Not when installing but there is a black border around the app as shown in the screenshot. Idk how to fix it. Any help would be appreciated im assuming its something missing.
![Screenshot_20231012_010544](https://github.com/mijorus/gearlever/assets/15163316/592a6e54-8a14-4e9e-9ae3-765ad12f0cc5)

**Comment by mijorus** [comment]
Hi,
This doesn't seem to be an issue regarding Gear lever, but rather your compositor messing up something... Maybe the shadow.

Could you please specify your current configuration?

**Comment by wingedonezero** [comment]
Yes i am on kde debian 12 with wayland. But in flatseal it does have all the options enabled. And i have also tryed  x session and didnt change anything. Ive tested other apps using gtk and none have this issue. Its also weird because if i click the black area it acts liek it isnt ther and clicks what evers behind it. I found a few issues that were similar and it had to do with theming in other apps. https://github.com/alainm23/planify/issues/268

**Comment by wingedonezero** [comment]
Also whats weird is it only happens int he main screen not in the install screen. Screenshot below. 
![Screenshot_20231012_023617](https://github.com/mijorus/gearlever/assets/15163316/52fa48a5-0ca5-426e-b14b-a14c29ff3fe6)

**Comment by wingedonezero** [comment]
Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.5.5 (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 3900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 550 / 550 Series

**Comment by mijorus** [comment]
I'm sorry but I don't think that this issue is related to Gear Lever
