### ISSUE TITLE
Option to remove from app menu/drawer (without uninstalling)

### ISSUE THREAD

**Issue by rene-coty** [mijorus/gearlever#41]
I wanted to remove an appimage from my app menu (because the icon was to inconsistent + title was too long) and gearlever uninstalled it completely. I expected the app to just remove the desktop file/icon from the drawer and not remove it from my system.. this should be added as an option because users will expect to be able to reverse the move to app menu/drawer

**Comment by mijorus** [comment]
I'm sorry but I don't see how this option can be useful in an app like GearLever.
