### ISSUE TITLE
Option to edit desktop file (icon + name)

### ISSUE THREAD

**Issue by rene-coty** [mijorus/gearlever#43]
It would be great if Gearlever allowed to edit the appimage's icon or name/title, as it already offers the ability to create a shortcut in the app menu/drawer

**Comment by 00sapo** [comment]
It would also be better if we could edit the whole content of the  `.desktop` file (it could still be identified via its filename). This would allow much more customizability. \

For instance, I need to edit the environment variables, but I lose them every time the app is updated. Another option would be to edit the command itself: I want to run it with `prime-run` in front of it for running on GPU. I know Gnome has an option that automatically sets those environment variables for specific `.desktop` files. Maybe there could be an option for it, like `Nvidia GPU offload` which sets `__NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia`.

**Comment by mijorus** [comment]
@00sapo the ability to set environnement variabile is coming soon with an update

**Comment by mijorus** [comment]
@00sapo version 1.1 includes an option to edit and add environment variables

**Comment by cvpsmith** [comment]
How do you set a mime type for a program?  Does the program create .desktop files somewhere?

**Comment by mijorus** [comment]
> Does the program create .desktop files somewhere?

Yes, it creates desktop files under ~/.local/share/applications

> How do you set a mime type for a program? 

What to you mean my that?

**Comment by mijorus** [comment]
Anyway, I'm sorry but the option to edit icon and app names is not coming to Gear Lever. This app is designed to give you a seamless experience when dealing with appimages, there are other tools to customize icons etc..

While, as I learnt, editing command line options and environment variables is required for some apps in order to work, this is purely a customization feature.

Sorry
