### ISSUE TITLE
Appimage filenames are changed on update

### ISSUE THREAD

**Issue by Dnkhatri** [mijorus/gearlever#45]
Appimage filenames are changed on update this break any shortcut. Ie if the appimage is supposed to run on startup the link get broken

**Comment by mijorus** [comment]
Hi, 
can you please explain the problem a little more?

Also, can you point out the app that is causing problems?

Thank you

**Comment by Dnkhatri** [comment]
I had installed qbittorrent torrents files auto opened with it when we double click them. Then installed the update the new qbittorrent appimage has a different name so the links no longer work. You should use gearlever_qbittorrent.appimage instead of adding new extra characters when we update an app breaks continuity

**Comment by mijorus** [comment]
Right, now I see it.
Basically if you set an appimage as the default for a specific file extension, the setting is lost if the filename changes.

The extra characters are needed in order to avoid any possible conflict, but this issue can be worked around

**Comment by mijorus** [comment]
https://github.com/mijorus/gearlever/commit/781a6e11513f299c68acb6fc834b0cddcba956ac

This commit should fix the issue. 
While I still want to complete some testing before releasing, you can install this development version and give feedbacks.

https://github.com/flathub/it.mijorus.gearlever/pull/25
