### ISSUE TITLE
[Bug Report / Feature Request] Ability to add command line arguments

### ISSUE THREAD

**Issue by KaiserCalm** [mijorus/gearlever#48]
This app is really good for managing AppImages, however when you add command line arguments to the .desktop file the AppImage vanishes from Gear Lever.

Firstly I think it would be neat if the command line options allowed the app to still show up in gear lever. As some apps, like r2modman, where the developer says that a crashing issue for Linux won't be fixed and advises people to just use `--no-sandbox`, require command line arguments.

And secondly a feature that allowed adding and editing command line arguments in Gear Lever itself. It could look something like this:
![gear_lever_concept](https://github.com/mijorus/gearlever/assets/81613945/ab643512-0426-4784-9721-e622f4d58c4b)

Or maybe even something similar to what Flatseal does with environment variables, as in them being each in their own line:
![image](https://github.com/mijorus/gearlever/assets/81613945/a0ca5508-4e72-4725-8197-7bae70066c37)

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
