### ISSUE TITLE
Web clipping with UpNote worked on Rhino Linux - not on Fedora 39 Workstation (Gnome)

### ISSUE THREAD

**Issue by lbtbs** [mijorus/gearlever#49]
Web clipping in UpNote did not work for me on Fedora 39 Workstation (Gnome) when I tried the snap version. Then I tried the app image via app Gear Lever because I didn't find AppImageLauncher in Fedora's Software app. I had the same issue: the browser extension just opened UpNote but did not clipped anything. I tried integrating UpNote image app via Gear Lever on my old laptop running Rhino Linux - Ubuntu based - and the web clipping worked as on Windows (dual boot with Fedora on my new desktop pc). Then I uninstalled Gear Lever in Fedora's Software app, downloaded and installed the rpm package of AppImageLauncher and used it for integrating and launching UpNote app image. Finally, the web clipping worked. So all worked for me on Rhino Linux, but not on Fedora.

**Comment by mijorus** [comment]
Hi, thanks for reporting the issue.

This is in some way related to https://github.com/mijorus/gearlever/issues/48, so please expect an update soon

**Comment by lbtbs** [comment]
Thank you, for your fast action, but I don"t know, when I"ll give Gear Lever another chance. If I do it one day then I let you know if the updated version worked for me.

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
