### ISSUE TITLE
Application not added to app menu

### ISSUE THREAD

**Issue by rprego** [mijorus/gearlever#51]
On version 1.0.18, adding a new AppImage no longer seems to add an application menu to the system launcher menu where previous versions did. Fedora Kinoite 29 (KDE).

**Comment by mijorus** [comment]
Hi, 
can you please provide the appimage you are trying to install?

Thank you

**Comment by mijorus** [comment]
I think it was my bad, this should fix the issue

https://github.com/mijorus/gearlever/commit/35003fb246c4df667a3528b58de06b9fa90f7dc8

**Comment by mijorus** [comment]
Version .19 should address this issue.
Let me know if the issue was fixed for you.


Thank you

**Comment by rprego** [comment]
That appears to have fixed it!

**Comment by rprego** [comment]
That appears to have fixed it in version .19

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
