### ISSUE TITLE
Option to set environment variables 

### ISSUE THREAD

**Issue by doinkythederp** [mijorus/gearlever#53]
I have an AppImage that needs the `GDK_BACKEND=x11` environment variable set. I can't use the app in Gear lever because there is no option to change the environment for a certain AppImage. An implementation that would work for me would be an option to add custom environment variables for a certain AppImage, setting the `Exec` field in the desktop configuration to `env VAR1=value /path/to/appimage`

**Comment by mijorus** [comment]
Version 1.1.0 added environment variables customization.

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
