### ISSUE TITLE
Consider changing ~/AppImages location to ~/.AppImages

### ISSUE THREAD

**Issue by fiftydinar** [mijorus/gearlever#59]
Reason?

Visible folders in home should be populated by folders with media & documents (Documents, Downloads, Music, Pictures, Videos etc.)
While invisible files & folders contain configurations, data used by system or apps. They also can include portable app binaries, which AppImages are.

This will make separation between them cleaner.

**Comment by lwbt** [comment]
In them mean time one can add the folder name to `.hidden` file in the home directory. Sorry for stating the obvious, but some users may not know about this.

**Comment by mijorus** [comment]
Hi, 
you can change the default folder for AppImages in the settings: there is an option just for that.

If you knew about this and you were suggesting to change the default path, I'm sorry but I am not a big fan of hiding content to the user.

Furthermore, many tutorials already suggest to use folders like ~/Appimages or ~/Applications for `.appimages` files, so they kinda became the "standard locations" for `.appimage` files.
