### ISSUE TITLE
[feature] bulk import appimages

### ISSUE THREAD

**Issue by AeroBliss** [mijorus/gearlever#60]
I have a folder of 19 AppImages, having a bulk import feature would be nice so I and others wouldn't need to import AppImages one by one.

**Comment by mijorus** [comment]
Hi, 
version 1.4.0 added the ability to import multiple appimages at once, both by drag and drog or by usintg the Open button on the top-left corner.

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
