### ISSUE TITLE
Remember size, position and mode of the main window

### ISSUE THREAD

**Issue by lwbt** [mijorus/gearlever#61]
Hello, thank you for developing this app.

I found that the main window does not remember its size, position and mode (maximized or not). I run the Flatpak version of the app. I compared the contents of `~/.var/app/it.mijorus/gearlever/config/glib-2.0/settings/keyfile` with Lollypop which behaves as expected. Settings for the file picker a properly saved and restored.

Why would one want that? In some environments where one prefers to run all apps in maximized mode on small screens it allows for a consistent behavior.

Thank you very much for your time.

**Comment by mijorus** [comment]
Hi, 
this seems to be more something that has to do with your desktop configuration then with Gear Lever

**Comment by lwbt** [comment]
Actually, there is nothing that you could call a desktop in the environment I'm referring to. I run that application from Steam Deck game mode. (Often I run a terminal on a Steam Deck from game mode and inside that terminal Flatpak apps and other things.)

I'm not asking you to refactor your app for libhandy or whatever Purism's Librem5 and similar phones do these days. That would be worth another discussion which I have no time for at the moment. (I had I Librem5 until a few weeks ago though.)

Please kindly reconsider saving and reading the window state. See the image attached.

Otherwise you may close this issue as opinionated. Thank you very much for your time. ![PXL_20240210_152009255~2.jpg](https://github.com/mijorus/gearlever/assets/16510356/80f1b96d-cc41-4a03-8e45-08cd031421df)

**Comment by mijorus** [comment]
I'll see what I can do

**Comment by mijorus** [comment]
Hi, 
I can't save the position of the window (Wayland... 😤) but I can save if the window was maximized or not.
This feature will be available in version 1.3.0

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
