### ISSUE TITLE
Doc Upgrade Process

### ISSUE THREAD

**Issue by solariz** [mijorus/gearlever#63]
Hi,

what is the supposed way to upgrade AppImages managed by Gearlever?

I use it recently and struggeling to find the right way to update a installed app image, do I manually need to replace the renamed appimage in the folder or is there some "autmagical" way to replace it via UI?

The docs are not very clear about the go to process definition on how you are supposed to update an appimage.

Thanks !

**Comment by mijorus** [comment]
Hi @solariz ,
nothing is magical in this world, or so I think.

Anyway, if you need to update an appimage, you can simply download the new version and open the file with Gear Lever.
Gear Lever will detect if the new app is a new release of an existing app, and will ask an update confirmation.

That's it.

**Comment by mijorus** [comment]
If this works for you, please close the bug report

**Comment by tr1p0p** [comment]
The point of this issues is "Why there's no doc anywhere to just... show how to update a appimage ?" Feature that literally on the readme ?

So, yeah : how can, with this app that state this feature in is readme, update a app ?

**Comment by ivan-hc** [comment]
@solariz There are several ways to upgrade appimages, but the more convenient one is also the less adopted by the developers, i.e. including update info into the bundle itself, so it can be updated using zsync or appimageupdatetool.

About the 5% of all developers are including this officially supported feature.

However, I've my own method, the only one that works for surewith all packages, appimages and not: put a script near the package that compares and point the versions in local and at the upstream.

This is what I do in my project, "AM" Application Manager, at https://github.com/ivan-hc/AM , to manage all my 1900+ installation scripts for appimages and standalone apps for x86_64 , and almost all of them are updatable!

This is the catalogue I use (and own) https://portable-linux-apps.github.io , @mijorus if you like it, you could integrate it into your project, to improve it, only that I don't only install appimage packages (which are over 1800) but also portable apps, such as Firefox, Blender, NodeJS... from the upstream's official zip/tar package. Each page of this catalogue have a URL to the source of that package.

I also develop appimage packages and scripts to create your own in my repositories. Check it out.

**Comment by ivan-hc** [comment]
@mijorus if you have a .deb or AUR package for GearLever and you're interested, I can try to build an AppImage of your app, I did the same for [Bottles](https://github.com/ivan-hc/Bottles-appimage). In this way we can also try to resolve the paradox whereby to manage AppImage packages you need a Flatpak. Contact me, sono italiano anch'io.

**Comment by mijorus** [comment]
Hi @ivan-hc ,
I don't currently have an AUR or a `.deb` release, and I am not really interesting in making one.
However, I might be considering creating an AppImage release for GearLever, but I don't really know where to start.

If you want to help me out, please contact me [here (email)](mailto:lorenzo@mijorus.it)
