### ISSUE TITLE
Unable to install TOTK Optimizer

### ISSUE THREAD

**Issue by Schmene** [mijorus/gearlever#64]
Stuck on "Installing..." when trying to import TOTK Optimizer appimg from https://github.com/MaxLastBreath/TOTK-mods/releases/tag/manager-1.5.5
![image](https://github.com/mijorus/gearlever/assets/36028029/0c55a06c-7df9-4ece-b442-df41c5781b00)
`OS: Fedora Linux 39 (KDE Plasma) x86_64`
`DE: Plasma 5.27.10`
[gearlever.log](https://github.com/mijorus/gearlever/files/14316024/gearlever.log)

**Comment by mijorus** [comment]
Hi @Schmene ,
This application is not an app image, it is an executable which was re-named ".appimage".

From the pipeline of the project on GitHub, it is clear that they are not even using appimagetool.
