### ISSUE TITLE
I lost ALL apps, still have the .desktop link, but nothing on the app

### ISSUE THREAD

**Issue by tr1p0p** [mijorus/gearlever#65]
Hi, so i use Gearlever since quite some times now.

But one day, it just decide that it will get rid of **all** apps. I still got my folder of apps, there's still some appimage that have been renaming by gearlever, and the app still show on launcher, .desktop link still here.

![image](https://github.com/mijorus/gearlever/assets/37407065/f46ac715-9c21-4eb2-90b5-3a47fe4e55e9)

So why i start with a blank app, no apps at all ?

![image](https://github.com/mijorus/gearlever/assets/37407065/6e2ef454-0689-403e-82a5-2dd5a19e72f6) 
![image](https://github.com/mijorus/gearlever/assets/37407065/0c9d3a58-93d3-40a3-99a9-fc577a2a3be8)

So how can i fix that ? I cannot edit the .desktop anymore, cannot update...

Appimages, in all this years, still not have basic of app packages (like easy auto-update, and way to... have it on app launcher of our desktop)

**Comment by mijorus** [comment]
Hi @tr1p0p ,
Could you please go into the settings, enable the "Debug Logs" switch, restart Gear Lever and send the gearlever.log file?

You can find this file from by clicking on "Open Log File" from the main menu.

Thank you

**Comment by tr1p0p** [comment]
> Hi @tr1p0p , Could you please go into the settings, enable the "Debug Logs" switch, restart Gear Lever and send the gearlever.log file?
> 
> You can find this file from by clicking on "Open Log File" from the main menu.
> 
> Thank you

How, sorry, i should think of it. Here it is : [gearlever.log](https://github.com/mijorus/gearlever/files/14322949/gearlever.log)

It seem around root permission and stuff like that ? It seem it remove a lots of .desktop file ? (but still have it on a lots of app)

**Comment by mijorus** [comment]
Which OS are you using?

**Comment by mijorus** [comment]
Also, sorry for the asking again, could you please run the app from the terminal using the following command and paste any output error here on GitHub?


`flatpak run it.mijorus.gearlever`

**Comment by tr1p0p** [comment]
Using Fedora 39, flathub install.

Here the logs : 

Logging to file /home/tripop/.var/app/it.mijorus.gearlever/cache/logs/gearlever.log

(gearlever:2): Gtk-WARNING **: 15:58:54.458: Unknown key gtk-modules in /home/tripop/.var/app/it.mijorus.gearlever/config/gtk-4.0/settings.ini

**Comment by mijorus** [comment]
That's weird.
Are you sure you haven't modified some permissions using tools like Flat seal?

Also, from your screenshot I can see a folder called `icons`.

This is not the default one that Gear Lever creates (it should be a hidden folder `.icon`. 

Have you maybe modified it?

**Comment by tr1p0p** [comment]
> That's weird. I don't see anything wrong in the logs. Are you sure you haven't modified some permissions using tools like Flat seal?
> 
> Also, from your screenshot I can see a folder called `icons`.
> 
> This is not the default one that Gear Lever creates (it should be a hidden folder `.icons`)
> 
> Have you maybe modified it?

I think it mostly because i try appimagepool and put this path on it ? (but i uninstalled this app quickly)

But no i didn't do any modification on flatseal and all.

**Comment by mijorus** [comment]
Do you see the desktop files under ~/.local/share/applications/ ?

That would be the last thing to check...

**Comment by tr1p0p** [comment]
There's still a lot : 
![image](https://github.com/mijorus/gearlever/assets/37407065/c0bd6f26-57cc-46b1-b344-68df436f8d97)
 (off course, still not showing on gear lever, for whatever reasons)
 
 Here one of the .desktop :
 
```
 [Desktop Entry]
Name=JoalDesktop
Exec=/home/tripop/Apps/gearlever_joaldesktop_5121c8.appimage
Terminal=false
Type=Application
Icon=/home/tripop/Apps/.icons/gearlever_joaldesktop_5121c8.appimage
StartupWMClass=JoalDesktop
X-AppImage-Version=2.0.12
Comment=A tool to fake your torrent tracker upload
Categories=Utility;
```

Did i just loose all app made by gear lever now ? I have to delete manually every .desktop files and re-do all ? Why Appimages are *so* difficult and weird ? Difficult to integrate to a system, difficult to update, and difficult to *keep* on a system.

**Comment by mijorus** [comment]
> Did i just loose all app made by gear lever now ? I have to delete manually every .desktop files and re-do all ? Why Appimages are *so* difficult and weird ? Difficult to integrate to a system, difficult to update, and difficult to *keep* on a system.

Dude, I'm not the developer of the appimage format, I'm just someone trying to do his best to make them less painful.

Go and ask them why they are so difficult to integrate.


You haven't lost anything, your data is still there, your apps are still there.

Anyway, there might be multiple reasons why they are not showing up.

If you could please send me the log file, I can try to look into that.

**Comment by tr1p0p** [comment]
Sorry i know you're not the dev of appimage it's was not meant to be understood like that. It was more a frustrated statement around this format.

So yeah, anyway, here's the logs : [gearlever.log](https://github.com/mijorus/gearlever/files/14794904/gearlever.log)

**Comment by KibSquib48** [comment]
I'm having this issue too after an update from Flathub tonight

The appimage is present in my `~/.AppImages` folder and its .desktop file shows up in ~/.local/share/applications just fine, but it's not in Gear Lever

Here's my log: [gearlever.log](https://github.com/mijorus/gearlever/files/15329027/gearlever.log)

**Comment by mijorus** [comment]
I'm so

> I'm having this issue too after an update from Flathub tonight
> 
> The appimage is present in my `~/.AppImages` folder and its .desktop file shows up in ~/.local/share/applications just fine, but it's not in Gear Lever
> 
> Here's my log: [gearlever.log](https://github.com/mijorus/gearlever/files/15329027/gearlever.log)

I'm sorry about this guys, that was a mistake I shipped in the lastest update.
Your apps and settings are safe, they are just not showing up.

A fix is coming out soon

**Comment by KibSquib48** [comment]
Latest update fixed it, thank you!

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
