### ISSUE TITLE
Beekeeper Studio AppImage creates two entries

### ISSUE THREAD

**Issue by PHLAK** [mijorus/gearlever#68]
After importing the AppImage for [Beekeeper Studio](https://www.beekeeperstudio.io/) I get two entries in the Installed Applications list.

<p align="center">
  <img src="https://github.com/mijorus/gearlever/assets/53531/2bd29be3-cabe-436b-ae33-368de0c50654" width="80%">
</p>

There are also two entries in the GNOME app menu when searching for "Beekeeper" (one with an icon and one without) but strangely only one in the full app menu list.

<p align="center">
  <img src="https://github.com/mijorus/gearlever/assets/53531/9a052a56-db1c-4a5c-95db-a06b42219211" width="80%">
  <img src="https://github.com/mijorus/gearlever/assets/53531/4ee1fa7f-edc9-4106-b4b2-fc1dde26c938" width="80%">
</p>

The app will launch from either icon but the running app in my dock will only ever be the one without the icon (i.e. `Beekeeper Studio Ultimate (4.1.13)`).

<p align="center">
  <img src="https://github.com/mijorus/gearlever/assets/53531/68044f11-a304-4985-a300-ad93ca7fe2ef" width="80%">
</p>

**Comment by mijorus** [comment]
Ummm, not sure what is causing this issue, I think it might be some built-in update logics by beatkeeper. I have installed the app without issues really

**Comment by PHLAK** [comment]
@mijorus Is there any way for me to gather additional information that might help troubleshoot this? Maybe logs or something I could provide?

**Comment by mijorus** [comment]
> @mijorus Is there any way for me to gather additional information that might help troubleshoot this? Maybe logs or something I could provide?

 If you go into the settings, you can enable the debug logs. Then restart the app, and you should see a button called Open log file in the main menu.

**Comment by PHLAK** [comment]
I figured it out. I had some `.desktop` entries left in `~/.local/share/applications` that AppImageLauncher created. After removing those and "reinstalling" Beekeeper Studio through Gear Lever there is only one entry and it's working as expected.
