### ISSUE TITLE
Move and/or update operations don't work

### ISSUE THREAD

**Issue by warcayac** [mijorus/gearlever#69]
The first time I installed GearLever on **EndeavourOS** it moved Appimage files (downloaded into Download directory, if app existed over there then updated it) to my custom app directory when right-clicking on that appimage file, BUT after some updates it does work anymore. I have to open GearLever and select appimage file to move/update.

Is this intentional or is some additional configuration needed?

**Comment by mijorus** [comment]
No, it should still work, might be a bug

**Comment by warcayac** [comment]
it must be a bug because I just installed my OS again and this behavior persists.

**Comment by mijorus** [comment]
This should be related to https://github.com/mijorus/gearlever/issues/70

I'm sorry I didn't understand your problem at the beginning, version 1.4.2 should fix this issue
