### ISSUE TITLE
AppImage

### ISSUE THREAD

**Issue by probonopd** [mijorus/gearlever#7]
Hi @mijorus, have you thought about distributing your application as an AppImage? Then it would be useful for those of us who don't use Flatpak.

**Comment by probonopd** [comment]
Wouldn't it be more consequential then to offer it as an AppImage rather than as a Flatpak? I mean, it's a tool for AppImage users after all.

**Comment by mijorus** [comment]
Flatpak is preinstalled by default in most distros these days, and it's pretty well integrated in stores like Discover or GNOME Software.

This app is designed for people that don't know how to use AppImages or just don't want to go and grab tools like appimagelauncher (which doesn't even launch on the latest Ubuntu LTS).

Furthermore, I've never released an AppImage and after a long hour of attempts I think it's not worth the effort for the kind of UX I'm looking for.

I prefer focusing on just one release and optimise the app for that packaging format.

**Comment by probonopd** [comment]
AppImage does not need to be installed, also dowsn't need things like appimagelauncher. Just download an AppImage, set the executable bit, and double click the application.

Anyhow, it's obviously your decision, which I respect of course. It just strikes me as odd to deliver something for AppImages as anything else than an AppImage.

**Comment by mijorus** [comment]
> (I mean, if someone wanted to use Flatpak, they'd just use that and not care about AppImage...)

There are some apps only (officially) released as AppImage,  tools like NoSqlBooster or DBGate.
You can't always choose the programs you're going to use for your job.
