### ISSUE TITLE
File manager's "Open With Gear Lever" not working on version 1.4.1

### ISSUE THREAD

**Issue by brotenet** [mijorus/gearlever#70]
Using the Nemo file manager "Open With Gear Lever" on an .AppImage file is to not working on version 1.4.1.
The only actions that work are drag-and-drop and "Open" from GearLever's app menu.
I've tested with the following:

- Kernel: 5.15.0-100-generic x86_64 bits: 64 
- compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
- tk: GTK 3.24.33 
- wm: muffin vt: 7 
- dm: LightDM 1.30.0 
- Distro: Linux Mint 21.3 Virginia
- base: Ubuntu 22.04 jammy

Please refer to the attached video.
https://github.com/mijorus/gearlever/assets/4510965/2f74e492-c8e2-4785-b728-049143937f79

**Comment by mijorus** [comment]
Hi, version 1.4.2 should fix this issue, it will be released in a few hours

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
