### ISSUE TITLE
Unable to open any AppImage

### ISSUE THREAD

**Issue by xlbingo10** [mijorus/gearlever#71]
I am completely unable to open any AppImage file. Attatched the `gearlever.log` file, though I am unable to parse anything useful from it.
[gearlever.log](https://github.com/mijorus/gearlever/files/14577171/gearlever.log)
Gear lever version is 1.4.3, I am using the newest version of Arch Linux on a fresh install.

**Comment by mijorus** [comment]
Hi, could you please enable the debug logs from the settings and attach the new log file here?

**Comment by xlbingo10** [comment]
[gearlever.log](https://github.com/mijorus/gearlever/files/14605738/gearlever.log)

**Comment by xlbingo10** [comment]
Solved. I didn't have FUSE installed.
