### ISSUE TITLE
[Feature Request] Allow launching the appimage INSIDE the flatpak container, but giving it access to files OUTSIDE the container

### ISSUE THREAD

**Issue by xplshn** [mijorus/gearlever#74]
Allow launching the appimage INSIDE the flatpak container, but giving it access to files OUTSIDE the container so that people using Musl based distros like Alpine Linux, Void, etc can use your Flatpak as a means to run AppImages in their systems, given that Flatpak runtimes come with GLibc inside, which is part of the why every runtime weights about 300 megs. Thanks!

**Comment by mijorus** [comment]
I'm sorry, but I am not implementing this feature any time soon.
