### ISSUE TITLE
[Feature Request] Ability to rename the .desktop files GearLever creates for appimages

### ISSUE THREAD

**Issue by AstralPhnx** [mijorus/gearlever#77]
This may seem a bit silly but there is very much a reason here. Some applications (Like Vesktop for example) run their tray notifications system in a way that requires their .desktop file to be named in a specific way (in this case vesktop.desktop).

If an appimage is installed or managed via GearLever however, GearLever defaults to its own naming scheme for .desktop files which is fine the majority of the time but in a situation like this it suddenly means I'm unable to get something like tray notifications working because of how that whole area functions (and this is arguably more the fault of electron to be honest but you know how it is)

**Comment by mijorus** [comment]
Hi @AstralPhnx ,
you can't rename the desktop file with Gear Lever, however there is an option in the settings that changes the default behavior, with that enabled, desktop files will be saved without prefixes.

![image](https://github.com/mijorus/gearlever/assets/39067225/368ee95a-0a8a-4a78-bf2b-7c9432a98900)
