### ISSUE TITLE
Make app icon shading consistent with other GNOME app icons

### ISSUE THREAD

**Issue by bragefuglseth** [mijorus/gearlever#8]
The icon is really well executed! GNOME icons usually have upward-facing surfaces shaded more lightly than forward-facing ones. I'd just make the top chin of the arrow lighter and the "main" surface of it darker to follow this convention.

**Comment by astersnake** [comment]
This should work in any desktop environment, not just GNOME.

**Comment by bragefuglseth** [comment]
This issue is just about an aesthetic detail on the app icon. GNOME has a unified app icon style, which this app attempts to follow, so I thought I should point it out. The app will still work fine in any desktop environment :)
