### ISSUE TITLE
[Flatpak] Osu does not launch

### ISSUE THREAD

**Issue by cassiofb-dev** [mijorus/gearlever#82]
Hi, first of all thanks for this awesome project!

I mostly use flatpak to run things but many devs use app image as official distribution so I thought it would be amazing to execute app images inside flatpak sandbox!

I tried to play osu but it does not start, here are the steps:
1. I clicked the launch button
2. For some seconds the button title changed to "launching..."
3. The button title changed to "launch"

I clicked on enable debug logs to provide a better log file, here is it: [gearlever.log](https://github.com/mijorus/gearlever/files/15445957/gearlever.log)

**Comment by mijorus** [comment]
Judging from your logs, this should't be related, but the latest version (1.6.0) fixed an issue with apps like Osu! that had special characters in the name

**Comment by cassiofb-dev** [comment]
Hi, yeah. I upgraded to 1.6.0 (the latest version today) and I'm getting the same behavior.

**Comment by TuxDeluxe** [comment]
I've seen this happen on my system when I did not have FUSE installed. Because gearlever does not ship with fuse, if it isn't installed on your system these app images will not launch. Is it possible to install fuse and give it another try?

**Comment by cassiofb-dev** [comment]
@TuxDeluxe , indeed I didnt have fuse installed. I installed it and the same thing happened, when I tried to run in terminal I got app image error but that was expected because I'm using Alpine. Is there anyway to check logs when gearlever runs appimages on flatpak sandbox?

Here is the image with the error outside flatpak sandbox:

![image](https://github.com/mijorus/gearlever/assets/61878987/74fe0885-0378-4b92-9e53-e7bb168cff68)

**Comment by TuxDeluxe** [comment]
Yeah, because app images sometimes don’t work on alpine, they won’t work through gearlever either. Seems like a problem with how osu relies on glibc rather than musl.

**Comment by cassiofb-dev** [comment]
@TuxDeluxe yeah, I thought the app image was executed in flatpak sandbox. Does it executes on the host system? If so I think there's really nothing that can be done.

App Image doesn't support Alpine and other distros not using glibc at all and I thought this project made it execute inside the sandbox. This is the issue I found on App Image project: https://github.com/AppImage/AppImageKit/issues/877

**Comment by TuxDeluxe** [comment]
@cassiofb-dev gearlever does sandbox some commands but it uses 

> flatpak-spawn —host

 to run app images which essentially runs them on the hosts machine.

**Comment by mijorus** [comment]
> @TuxDeluxe yeah, I thought the app image was executed in flatpak sandbox. Does it executes on the host system? If so I think there's really nothing that can be done.
> 
> App Image doesn't support Alpine and other distros not using glibc at all and I thought this project made it execute inside the sandbox. This is the issue I found on App Image project: https://github.com/AppImage/AppImageKit/issues/877

They don't, as others have suggested.
App images are launched on the host system, the goal of this project is just to automate the "desktop file creation" part.
