### ISSUE TITLE
Can't open appimages in KDE dolphin file manager

### ISSUE THREAD

**Issue by NRobert-jmdrgg** [mijorus/gearlever#85]
When I try to open an appimage file inside dolphin it prompts me if I want to execute it or not, instead of opening it with gear lever. 

It opens correctly when I click on "open with gear lever" in the context menu.

I have set the file association to open AppImage files with Gear lever.

![Screenshot_20240602_122738](https://github.com/mijorus/gearlever/assets/79148362/c73016fb-18f2-465f-9f24-fee4de9b7d73)

![Screenshot_20240602_122620](https://github.com/mijorus/gearlever/assets/79148362/85001318-e066-4724-b834-1b86ee27b299)

OS: Debian 12 stable
Dolphin Version: 22.12.3
KDE plasma version: 5.27.5
KDE framework version: 5.103.0
Qt version: 5.15.8

**Comment by mijorus** [comment]
Hi, 
your app might have been flagged as an executable, that's why your OS is launching it directly.
Gear Lever itself marks apps as executables if you select "Lunch" without integrating them first.

Unfortunately, is behaviour cannot be changed.
