### ISSUE TITLE
gear lever bloats /tmp directory

### ISSUE THREAD

**Issue by wohltat** [mijorus/gearlever#86]
I tried gear leaver  with 5 AppImages and it froze. I was also wondering why my system got very sluggish.
Then i found that it completely filled my `/tmp` with 8GB of data.

It seems to copy my Application folder.
I think this is not the way the `/tmp` folder should used.

**Comment by mijorus** [comment]
Hi,
This behaviour is a consequence of how Gear Lever used to work at the very beginning.

I'm aware of this, I'll see what I can do.

**Comment by wohltat** [comment]
In case this has changed already, I have this behavior although I'm on manjaro/arch (rolling release).

Gear lever version 1.5.4

**Comment by mijorus** [comment]
version 1.6.0 which fixes this issue, was pushed on flathub

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
