### ISSUE TITLE
Button to change AppImage icon

### ISSUE THREAD

**Issue by stankovictab** [mijorus/gearlever#88]
If we can already replace the icon of an AppImage in the `.icons/` folder and have it instantly reflect in the `.desktop` file, and therefore the desktop environment, I think it would be nice to have the option to change it in the Gear Lever UI, which will basically do the exact same thing. 
Maybe a button to open the DE file picker, or just a simple drag and drop into the opened AppImage info screen. 
Obviously the Reload metadata button is useful to reset the icon.

**Comment by mijorus** [comment]
Hi, 
I'm sorry but I have no plans to implement this feature.
I think that a tool like Gear Lever should just be an helper to integrate appimages, just like an app store.
These app should then run as the original developer intended to.
