### ISSUE TITLE
Allow override for StartupWMClass

### ISSUE THREAD

**Issue by fwosar** [mijorus/gearlever#93]
It would be helpful if you can manually specify the StartupWMClass for the generated `.desktop` file. The reason being that a lot of AppImages unfortunately have the wrong value set, causing icons to be missing on Wayland specifically. It is possible to edit the `.desktop` file manually later, but whenever you refresh the meta information (for example after an update) you end up with messed up icons again.

**Comment by mijorus** [comment]
Hi,
Gear Lever is meant to make appimages easy to integrate, it shouldn't make any assumptions on how the app should run.

Gear Lever should clone all the entries from the original desktop to the desktop file it generates.
If the StartupWMClass entry is present on the source file but is missing, that is a bug.

It would be hard for me to decide how to name the StartupWMClass, hoping that this doesn't introduce other bugs somewhere.

My obvious suggestion would be to open an issue to the app development 🙃
