### ISSUE TITLE
Add the feature to (optionally) retain environment variables when updating an appimage

### ISSUE THREAD

**Issue by jtl5770** [mijorus/gearlever#96]
Currently it is able to set environment variables for appimages when installing them with gearlever, but they are lost whenever I update the appimage (by using "replace" when installing them).

It would be very convenient if exiting variable definitions would not be lost each time. This could be done via a preference or an additional dialogue each time an appimage with env vars is replaced.

**Comment by mijorus** [comment]
I think that env variables should be kept by default when updating using Replace, no extra dialog required, as this should have been the correct behavior from the start.
The next update will fix this issue, thank you

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus
