### ISSUE TITLE
Issue: Gear Lever won't load or install AppImages

### ISSUE THREAD

**Issue by MaCroX95** [mijorus/gearlever#98]
So I'm having this weird issue, I went ahead and installed fresh copy of Fedora 40 Silverblue and on my laptop Gear Lever worked fine and then I re-did basically same installation procedure on my main PC and Gear Lever won't load AppImages. It worked for me on this PC on the previous Fedora Silverblue install.

EDIT: My setup is Fedora 40 Silverblue, all AMD hardware, running stock kernel and current MESA drivers, nothing special going on there.

This is how it looks when I try to open AppImage with Gear Lever, only infinite spinning circle, doesn't move forward:
![image](https://github.com/mijorus/gearlever/assets/21268648/7db2c9fe-006b-4815-b2e6-d83aea012dc3)

And this is the output that I get from terminal when running the app through terminal.
```
flatpak run it.mijorus.gearlever
Logging to file /var/home/marko/.var/app/it.mijorus.gearlever/cache/logs/gearlever.log
Exception in thread Thread-1 (load):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/gearlever/gearlever/AppDetails.py", line 207, in load
    generation = self.provider.get_appimage_generation(self.app_list_element)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/providers/AppImageProvider.py", line 476, in get_appimage_generation
    if terminal.host_sh(['which', 'strings']):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/gearlever/gearlever/lib/terminal.py", line 19, in host_sh
    raise e
  File "/app/share/gearlever/gearlever/lib/terminal.py", line 14, in host_sh
    output.check_returncode()
  File "/usr/lib/python3.11/subprocess.py", line 502, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['flatpak-spawn', '--host', 'which', 'strings']' returned non-zero exit status 1.
```

Could anyone help or assist with troubleshooting?

**Comment by MaCroX95** [comment]
UPDATE: This seems to be a regression in latest versions, updated back to 1.5.X series and works fine now.

**Comment by mijorus** [comment]
> UPDATE: This seems to be a regression in latest versions, updated back to 1.5.X series and works fine now.

Hi, the attached log is clear enough, I'll implement a fix soon

**Comment by mijorus** [comment]
Hi, version 1.6.4 will  fix this, thanks for reporting

**Comment by MaCroX95** [comment]
> Hi, version 1.6.4 will fix this, thanks for reporting

Thank you! Really awesome utility app! All other AppImage "integration apps" went to deeply into the system and caused nothing but trouble for me, including performance issues... This does just enough and works great!

**Comment by mijorus** [comment]
> > Hi, version 1.6.4 will fix this, thanks for reporting
> 
> Thank you! Really awesome utility app! All other AppImage "integration apps" went to deeply into the system and caused nothing but trouble for me, including performance issues... This does just enough and works great!

thank you, please update this issue if the bug is fixed for you

**Comment by MaCroX95** [comment]
Confirming fixed!
