### ISSUE TITLE
Launch apps using appimage-run for nixos

### ISSUE THREAD

**Issue by tacostrange** [mijorus/gearlever#99]
[Nixos requires AppImages](https://nixos.wiki/wiki/Appimage) to be run with `appimage-run` 
Can the option be added to use this interpreter for launching an app?

**Comment by mijorus** [comment]
I'll work on it

**Comment by mijorus** [comment]
I have a development build right here, but it's not working for me as the `appimage-run` utility gets cleared on every session.
How does it work on nix os? I don't know this OS, sorry


```
flatpak install --user https://dl.flathub.org/build-repo/113859/it.mijorus.gearlever.flatpakref
```

**Comment by tacostrange** [comment]
appimage-run gets installed as a system package.
You can add the package `appimage-run` to the configuration file or install it with
```
nix-env -iA nixos.appimage-run
```
then 
```
appimage-run ./ondsel.appimage & 
```

**Comment by mijorus** [comment]
> appimage-run gets installed as a system package. You can add the package `appimage-run` to the configuration file or install it with
> 
> ```
> nix-env -iA nixos.appimage-run
> ```
> 
> then
> 
> ```
> appimage-run ./ondsel.appimage & 
> ```

Can you try this development version and see if it works for you?

**Comment by mijorus** [comment]
I managed to get my vm working.
Version 1.6.5 will add support for NixOS

**Comment by mijorus** [comment]
Thanks for contributing with this bug report.

If you want to support my work, please consider a small donation.

https://ko-fi.com/mijorus

**Comment by pective** [comment]
do you have an estimate on when gear lever 1.6.5 would be released? im thinking of switching to nixos completely when it releases.

**Comment by mijorus** [comment]
It's already out

**Comment by dmchmk** [comment]
Hi, @mijorus !

Is there any option I need to enable to run appimages through Gear Lever? I have it working from cli:

![изображение](https://github.com/user-attachments/assets/6a35d635-4bf2-42b2-8efd-475b6b9d0b26)

But refuses to work from Gear Lever:

![изображение](https://github.com/user-attachments/assets/b46afbac-681e-45bb-b5e7-8931b2c56129)

(I even tried entering `appimage-run %f` into the "cli argument" field, but got the same result)

**Comment by dmchmk** [comment]
New addition - starting the AppImage from Gear Lever **before** installing it works for some reason:

![изображение](https://github.com/user-attachments/assets/8c300c93-26c1-4df6-9da8-9bc3293406b6)

But after installing throws a FUSE error
